#!/usr/bin/perl

    ########################################################################
    # Twisted Bot - Perl POE Based IRC Bot                                 #
    # Copyright (C) 2013  Keldo ( Twisted Development)                     #
    #                                                                      #
    # This program is free software: you can redistribute it and/or modify #
    # it under the terms of the GNU General Public License as published by #
    # the Free Software Foundation, either version 3 of the License, or    #
    #(at your option) any later version.                                   #
    #                                                                      #
    # This program is distributed in the hope that it will be useful,      #
    # but WITHOUT ANY WARRANTY; without even the implied warranty of       #
    # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the        #
    # GNU General Public License for more details.                         #
    #                                                                      #
    # You should have received a copy of the GNU General Public License    #
    # along with this program.  If not, see <http://www.gnu.org/licenses/>.#
    ########################################################################
    
use strict;
use warnings;

# If on Windows, Comment the following line out
#use constant PATH => $ENV{HOME} ."/rictus/";

use FindBin;
use lib "$FindBin::Bin/lib";
use POE::Component::IRC::Plugin::Rictus;

POE::Component::IRC::Plugin::Rictus->run(@ARGV);