name: Rictus-Bot
version: 0.1
version_from lib/POE::Component::IRC::Plugin::Rictus.pm
installdirs: site
requires:
		POE
		POE::Component::IRC
		Config::Simple
		DateTime
		HTTP:Request
		LWP::UserAgent
		LWP::Simple
		XML::RSS
		HTML::Strip

		distribution_type: module